import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemProvider";


import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Container from "@/app/components/Container";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-Light dark:bg-dark`}>
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem = {false}
          disableTransitionOnChange
        >
          <Container>
            <Navbar/>
        {children}
        </Container>
        <Footer/>
        </ThemeProvider>
        </body>
    </html>
  );
}
